# Project information
site_name: Weco AI
site_url: https://WecoAI.github.io/weco-python
site_author: Weco AI
site_description: >-
  Documentation for weco, a client facing API for interacting with the Weco AI function builder service.
docs_dir: docs
site_dir: site
use_directory_urls: true

# Repository
repo_name: weco-python
repo_url: https://github.com/WecoAI/weco-python
remote_branch: gh-pages
remote_name: origin

# Copyright
copyright: null

# Configuration
theme:
  name: material
  locale: en
  custom_dir: .overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.collapse
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - social
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Dark Mode

    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Light Mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    logo: custom/weco
  favicon: assets/weco.svg
  include_homepage_in_sidebar: true
  highlightjs: true
  hijs_languages:
    - python

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [weco]
          options:
            docstring_style: numpy
            separate_signature: true
            show_signature_annotations: false
            show_source: false
            heading_level: 2

# Customization
extra:
  social:
  # Weco AI
    - icon: fontawesome/solid/house
      link: https://weco.ai/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/WecoAI/weco-python
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WecoAI
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/weco-ai/
    
extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  # (1)!
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

# Extensions
markdown_extensions:
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

# Page treec
nav: 
  - 'About': index.md

  - 'Getting Started' :
    - 'Installation' : 'getting_started/installation.md'
    - 'Introduction' : 'getting_started/introduction.md'

  - 'Cookbook': 'cookbook/cookbook.md'

  - 'API Reference':
    - 'Reference Guide' : 'api/api.md'
    - 'WecoAI Client': api/client.md
    - 'WecoAI Functions': api/functional.md

  - 'Contributing': contributing.md
